### ISSUE TITLE
ReferenceError: frameworkPackagePath is not defined

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt-cli#101]
```shellsession
$ adapt ls
C:\Users\tom.greenfield\AppData\Roaming\nvm\v8.12.0\node_modules\adapt-cli\lib\Project.js:65
    return JsonLoader.readJSONSync(frameworkPackagePath);
                                   ^

ReferenceError: frameworkPackagePath is not defined
    at parse (C:\Users\tom.greenfield\AppData\Roaming\nvm\v8.12.0\node_modules\adapt-cli\lib\Project.js:65:36)
    at Project.<anonymous> (C:\Users\tom.greenfield\AppData\Roaming\nvm\v8.12.0\node_modules\adapt-cli\lib\Project.js:22:28)
    at Object.ls (C:\Users\tom.greenfield\AppData\Roaming\nvm\v8.12.0\node_modules\adapt-cli\lib\commands\ls.js:14:25)
    at AdaptConsoleApplication.do (C:\Users\tom.greenfield\AppData\Roaming\nvm\v8.12.0\node_modules\adapt-cli\lib\AdaptConsoleApplication.js:16:33)
    at Object.execute (C:\Users\tom.greenfield\AppData\Roaming\nvm\v8.12.0\node_modules\adapt-cli\lib\cli.js:25:11)
    at Object.<anonymous> (C:\Users\tom.greenfield\AppData\Roaming\nvm\v8.12.0\node_modules\adapt-cli\bin\adapt:3:33)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
```

**Comment by moloko** [comment]
also get similar issue when installing a plugin and choosing (y) in response to the 'Update the manifest' prompt
![2018-11-02 10_48_39-cmder](https://user-images.githubusercontent.com/1249597/47911351-21957c80-de8d-11e8-8906-5a0999f21841.png)

**Comment by moloko** [comment]
(running adapt-cli v2.1.1 on Node v8.11.3)
