### ISSUE TITLE
release/v5: create course fails to load plug-ins

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt-cli#118]
`adapt create course "My Course" release/v5` installs the correct fw branch but errors while trying to install the required plug-ins:
```
Error: { '0': Error: adapt-contrib-vanilla "release/v5" is not a valid constraint
    at new constructor (C:\XXX\AppData\Roaming\nvm\v8.12.0\node_modules\adapt-cli\lib\commands\install\InstallTarget.js:31:23)
    at C:\XXX\AppData\Roaming\nvm\v8.12.0\node_modules\adapt-cli\lib\commands\install.js:132:26
    at Array.forEach (<anonymous>)
    at createPlugins (C:\XXX\AppData\Roaming\nvm\v8.12.0\node_modules\adapt-cli\lib\commands\install.js:131:32)
    at _fulfilled (C:\XXX\AppData\Roaming\nvm\v8.12.0\node_modules\adapt-cli\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\XXX\AppData\Roaming\nvm\v8.12.0\node_modules\adapt-cli\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (C:\XXX\AppData\Roaming\nvm\v8.12.0\node_modules\adapt-cli\node_modules\q\q.js:816:13)
    at C:\XXX\AppData\Roaming\nvm\v8.12.0\node_modules\adapt-cli\node_modules\q\q.js:877:14
    at runSingle (C:\XXX\AppData\Roaming\nvm\v8.12.0\node_modules\adapt-cli\node_modules\q\q.js:137:13)
    at flush (C:\XXX\AppData\Roaming\nvm\v8.12.0\node_modules\adapt-cli\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9) } 
```
( However, `adapt create course "My Course" issue/1987` succeeds, installing the required plug-ins.)

adapt-cli: v2.1.8
Tested on Windows 10, node v8.12.0 using git bash
Tested on Ubuntu 18.04.1, node v10.16.2

**Comment by moloko** [comment]
@chucklorenz I think it might be more to do with how the plugins have been specified [here](https://github.com/adaptlearning/adapt_framework/blob/release/v5/adapt.json) than the fault of the CLI

**Comment by moloko** [comment]
I'm not sure the adapt cli has been set up to allow for plugins to be installed from a specific branch, only from tags or releases. If not then perhaps it should be, I can clearly see that it would be useful here!

**Comment by chucklorenz** [comment]
@moloko Yes, I'm sure you're correct. My work doesn't need this to be corrected--ended up downloading them manually. Not sure it's worth the time to update the adapt.json. Perhaps there is a value to others in this issue remaining visible until v5 is released? Your call when to close. Thanks!

**Comment by moloko** [comment]
Yes let's leave - possibly even convert to a feature request
