### ISSUE TITLE
Error: Cannot find module 'Q'

### ISSUE THREAD

**Issue by mauroka** [adaptlearning/adapt-cli#32]
Installing adapt-cli on Debian 8 shows the following error:
    throw err;
          ^
Error: Cannot find module 'Q'

To solve it I had to modify the file:
/usr/local/lib/node_modules/adapt-cli/lib/promise/install.js
and change the 'Q' for 'q' like this:
Q = require('q'),

I think this happens in all case sensitve systems like Linux, Mac OS, etc.

**Comment by dennis-learningpool** [comment]
@cajones can you give this a quick look - I encountered the same issue when attempting a fresh install of the authoring tool this morning

**Comment by aniketdharia** [comment]
is this issue fixed? I am still getting it. I tried today on a linux server.


module.js:340
    throw err;
          ^
Error: Cannot find module 'Q'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/adapt-cli/lib/promise/install.js:2:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by aniketdharia** [comment]
can we please just merge this "q" change so that the linux installations can proceed..

**Comment by dennis-learningpool** [comment]
Hi @aniketdharia,

The change has been tagged and released as 2.0.2, but this release needs to be published to the npm registry before it will be installable via npm. @oliverfoster has promised to do this as soon as he gets the chance.

**Comment by oliverfoster** [comment]
I'm on it. It'll be done by 10 this morning.
