### ISSUE TITLE
Urgent: installation broken on Node v8

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt-cli#81]
The `nodegit` dependency needs to be bumped up; the latest version is `0.20.3`. This is because Node v8 is imminently going to enter into [Long Term Support](https://github.com/nodejs/Release#release-schedule1).

**This will be a breaking change for users still running Node v4.** However, that version had its LTS ended back in April of this year and is now in maintenance.

Higher dependency tested working with Node v6.11.5 (current LTS) & v8.8.1 (LTS as of 31/10/17), on Windows 10.

This bug also impacts the [authoring tool](https://github.com/adaptlearning/adapt_authoring/pull/1689#issuecomment-321860621).

<details>
<summary>Error log</summary>

```console
$ npm install -g adapt-cli
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
C:\Users\tom.greenfield\AppData\Roaming\npm\adapt -> C:\Users\tom.greenfield\AppData\Roaming\npm\node_modules\adapt-cli\bin\adapt

> nodegit@0.16.0 install C:\Users\tom.greenfield\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.16.0-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for nodegit@0.16.0 and node@8.8.1 (node-v57 ABI) (falling back to source compile with node-gyp)
gyp
ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\tom.greenfield\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\tom.greenfield\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\tom.greenfield\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\tom.greenfield\\AppData\\Roaming\\npm\\node_modules\\adapt-cli\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\tom.greenfield\\AppData\\Roaming\\npm\\node_modules\\adapt-cli\\node_modules\\nodegit\\build\\Release\\nodegit.node" "--module_name=nodegit" "--module_path=C:\\Users\\tom.greenfield\\AppData\\Roaming\\npm\\node_modules\\adapt-cli\\node_modules\\nodegit\\build\\Release"
gyp ERR! cwd C:\Users\tom.greenfield\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\nodegit
gyp ERR! node -v v8.8.1
gyp ERR!
node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp
ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\tom.greenfield\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\tom.greenfield\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\tom.greenfield\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\nodegit\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\tom.greenfield\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp
ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\tom.greenfield\\AppData\\Roaming\\npm\\node_modules\\adapt-cli\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\tom.greenfield\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\nodegit
node-pre-gyp ERR! node -v v8.8.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\tom.greenfield\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\tom.greenfield\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\tom.greenfield\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\nodegit\build\Release' (1)
node-pre-gyp ERR! not ok
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.16.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tom.greenfield\AppData\Roaming\npm-cache\_logs\2017-10-27T13_22_11_020Z-debug.log
```

</details>

**Comment by rmalayter** [comment]
Why was this issue closed? It is still broken on Windows 10 install with latest node LTS release 8.11.3 LTS

```
node-pre-gyp
ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.16.0-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for nodegit@0.16.0 and node@8.11.3 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
gyp
ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```
